[package]
name = "ode_solvers"
version = "0.1.0"
authors = ["Sylvain Renevey <syl.renevey@gmail.com>"]
description = "ode-solvers is a toolbox to solve first order ordinary differential equations."
keywords = ["ode", "math", "solver", "equations"]
categories = ["science"]
license = "BSD-3-Clause"

[dependencies]
nalgebra = "0.16.0"
alga = "0.7.1"
